Import Debian changes 3.0-17
bash (3.0-17) unstable; urgency=low

  * Check that the device files /dev/std{in,out,err} are present at
    build time. Closes: #327477.
  * Remove html completion for w3m, users claim w3m to be a general viewer.
  * /etc/bash.bashrc: Avoid stat on /etc/debian_chroot, if not necessary.
    Closes: #303712.
  * debian/patches/wcontinued.dpatch: Update, fixing hangs in
    bash_completion (Junichi Uekawa). Closes: #318301.
  * Build-depend on texinfo (>= 4.8). Closes: #316066.

bash (3.0-16ubuntu3) breezy; urgency=low

  * Don't install .bash_logout again, doesn't clear the buffer and
    ps is not in required.

bash (3.0-16ubuntu2) breezy; urgency=low

  * Fix segmentation fault due to gcc optimization and longjmp. Patch
    by Jim Paris. Debian #293667.
  * Don't overwrite PROMPT_COMMAND in /etc/bash.bashrc. Ubuntu #15122.
    Closes #330889.
  * Install skeleton .bash_logout to clear the screen, when logging out
    from the console. Ubuntu #10149.

bash (3.0-16ubuntu1) breezy; urgency=low

  * bash_completion changes:
    - Add completion for evince.
    - Fix completion for aptitude (Ubuntu 12549).
      Closes: #293979, #325045, #327413.
    - Add completion for *.flac files in mplayer (closes: #304778).
    - Add completion for *.ott files for unzip and zipinfo (closes: #322481).
    - Add html completion for w3m.

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -74,7 +74,11 @@ min_conf_args += --host=$(DEB_HOST_GNU_TYPE)
 
 
 #build: bash-build minimal-build static-build preinst-build all-bashdb-build check
-build: bash-build minimal-build static-build preinst-build check
+build: before-build bash-build minimal-build static-build preinst-build check
+
+before-build:
+	: # see #327477, needed to have HAVE_DEV_STDIN defined
+	test -c /dev/stdin
 
 # ---------------------------------------------------------------------------
 # build standard bash
@@ -459,6 +463,10 @@ stamps/stamp-configure-$(build): stamps/stamp-patch-$(bash_src)
 	cd build-$(build) && \
 	    CC="$(CC)" CFLAGS="$(CFLAGS)" YACC="$(YACC)" \
 		../$(bash_src)/configure $(configure_args)
+	if ! grep -q '#define HAVE_DEV_STDIN 1' build-$(build)/config.h; then \
+	  echo "HAVE_DEV_STDIN not defined, abortig build"; \
+	  exit 1; \
+	fi
 	touch stamps/stamp-configure-$(build)
 
 patchdir	= debian/patches
@@ -505,6 +513,7 @@ debian_patches = \
 	update-multibyte-ifs \
 	speling \
 	bad-interp \
+	volatile-command \
 
 # all debian_patches, without bash205b-*
 # patches integrated in bashdb: builtins-shift, execute-cmd, man-arithmetic,
